### ISSUE TITLE
Bluetooth manager won't install

### ISSUE THREAD

**Issue by ntelogo** [wastis/LinuxAddonRepo#2]
Hi there, 
I have followed instructions, brought the repo in my kodi, clicking to install and getting the message:
> The dependency on xbmc.python version 3.0.0 could not be satisfied

What can be the solution? 

Kodi version: 18.7
OS: Raspbian 10
Kernel: 5.10.103
Python v.: 2.7.16
Python3 v: 3.7.3

**Comment by jnk22** [comment]
The error message you get says that you need Python 3, which afaik is only supported in Kodi 19+ but not in Kodi 18.7.

Are you able to update your Kodi to version 19.X (or even 20.2 which is the current stable version)?

This should probably solve your current issue.

**Comment by ntelogo** [comment]
You're correct. Upgrading to Kodi 19.4 solved this issue. 
Add on can be installed now.
